# Generated by Django 2.1.5 on 2019-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BinaryField(default=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
