# Generated by Django 2.1.5 on 2019-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20190328_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.TextField(default='djangodbmodelsfieldstextfield'),
        ),
    ]
