# Generated by Django 2.1.5 on 2019-03-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.TextField(default=False),
        ),
    ]
