# Generated by Django 2.1.5 on 2019-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('screen_size', models.IntegerField()),
                ('anouncement_date', models.DateField()),
                ('camera', models.IntegerField()),
                ('bluetooth', models.TextField()),
                ('ozu', models.IntegerField()),
            ],
        ),
    ]
