# Generated by Django 2.1.5 on 2019-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.TextField(default='PhoneX'),
            preserve_default=False,
        ),
    ]
