# Generated by Django 2.1.5 on 2019-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='url',
            field=models.TextField(default='beru.ru'),
        ),
    ]
