# Generated by Django 2.1.5 on 2019-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_setup',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
