# Generated by Django 2.1.5 on 2019-04-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_setup_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_setup',
            old_name='column_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='table_setup',
            old_name='column_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='table_setup',
            old_name='column_width',
            new_name='width',
        ),
    ]
