# Generated by Django 2.1.5 on 2019-04-17 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190417_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='commercial_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=256),
        ),
    ]
