# Generated by Django 2.1.5 on 2019-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('image', models.TextField(default='')),
                ('release_date', models.DateField(default=0)),
                ('lte_exists', models.TextField(default=False)),
                ('slug', models.TextField(default='djangodbmodelsfieldstextfield')),
            ],
        ),
    ]
